// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLtGP_7KgavWoJT5peHtV3JUqv1OnJUiU',
    appId: '1:412265538580:web:901e02e953e7f82c847301',
    messagingSenderId: '412265538580',
    projectId: 'lendly-6ee08',
    authDomain: 'lendly-6ee08.firebaseapp.com',
    storageBucket: 'lendly-6ee08.firebasestorage.app',
    measurementId: 'G-TK5BCQ7Y34',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtpGNARHCWih550xyvWgq2ZV2RJ8kaONc',
    appId: '1:412265538580:android:02548bc9e7fffe46847301',
    messagingSenderId: '412265538580',
    projectId: 'lendly-6ee08',
    storageBucket: 'lendly-6ee08.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhoJco97UYXQgc_UUe9sfeaP55aC6BHYU',
    appId: '1:412265538580:ios:e9781152ebad298e847301',
    messagingSenderId: '412265538580',
    projectId: 'lendly-6ee08',
    storageBucket: 'lendly-6ee08.firebasestorage.app',
    iosBundleId: 'com.example.lendly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhoJco97UYXQgc_UUe9sfeaP55aC6BHYU',
    appId: '1:412265538580:ios:e9781152ebad298e847301',
    messagingSenderId: '412265538580',
    projectId: 'lendly-6ee08',
    storageBucket: 'lendly-6ee08.firebasestorage.app',
    iosBundleId: 'com.example.lendly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLtGP_7KgavWoJT5peHtV3JUqv1OnJUiU',
    appId: '1:412265538580:web:71487d5bbfe56661847301',
    messagingSenderId: '412265538580',
    projectId: 'lendly-6ee08',
    authDomain: 'lendly-6ee08.firebaseapp.com',
    storageBucket: 'lendly-6ee08.firebasestorage.app',
    measurementId: 'G-XJLRE5K2LJ',
  );
}
